In [1]:
import pandas as pa
import re

In [2]:

def parse_hms(s):
    print(f"HMS  Parse {s}")
   
    parts = re.findall(r"([\d]+)[ ]([\d]+[\.][\d]+)", s)
    h, m_sec = map(float, parts[0])
    return h + m_sec / 60 # decimal hours


def parse_dec(s):
    print(f"DEC  Parse {s}")
    parts = re.findall(r"([+-])([\d]+)[ ]([\d]+)", s)[0]
    sign = -1 if parts[0].startswith("-") else 1
    deg = float("0" + parts[1])
    minu = float("0" + parts[2])
    return sign * (deg + minu / 60)

df=pa.read_csv("caldwell.txt",sep="\t")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   C               109 non-null    int64
 1   NGC             109 non-null    object
 2   Type            109 non-null    object
 3   Mag.            109 non-null    object
 4   Size arc_min    109 non-null    object
 5   Distance (ly)   109 non-null    object
 6   RA (hr_min)     109 non-null    object
 7   Dec (dg_min)    109 non-null    object
 8   Con             109 non-null    object
 9   Viewing Season  109 non-null    object
 10  Common Name     43 non-null     object
dtypes: int64(1), object(10)
memory usage: 9.5+ KB

In [3]:
#make sure all fields are populated
df["Common Name"]=df["Common Name"].fillna(df['NGC'])
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   C               109 non-null    int64
 1   NGC             109 non-null    object
 2   Type            109 non-null    object
 3   Mag.            109 non-null    object
 4   Size arc_min    109 non-null    object
 5   Distance (ly)   109 non-null    object
 6   RA (hr_min)     109 non-null    object
 7   Dec (dg_min)    109 non-null    object
 8   Con             109 non-null    object
 9   Viewing Season  109 non-null    object
 10  Common Name     109 non-null    object
dtypes: int64(1), object(10)
memory usage: 9.5+ KB

,C,NGC,Type,Mag.,Size arc_min,Distance (ly),RA (hr_min),Dec (dg_min),Con,Viewing Season,Common Name
0,1,188,Oc,8.1,14,4800,00 44.4,+85 20,Cep,autumn,188
1,2,40,Pl,11.6,0.6,3500,00 13.0,+72 32,Cep,autumn,Bow Tie Nebula
2,3,4236,Sb,9.7,21x7,7 million,12 16.7,+69 28,Dra,spring,4236
3,4,7023,Bn,6.8,18x18,1400,21 01.8,+68 12,Cep,autumn,Iris Nebula
4,5,IC 342,Sp,9.2,18x17,13 million,03 46.8,+68 06,Cam,winter,IC 342

In [4]:
df["RA_2"] = df["RA (hr_min)"].apply(parse_hms)/24.0*360.0
df["DEC_2"] = df["Dec (dg_min)"].apply(parse_dec)

HMS  Parse 00 44.4
HMS  Parse 00 13.0
HMS  Parse 12 16.7
HMS  Parse 21 01.8
HMS  Parse 03 46.8
HMS  Parse 17 58.6
HMS  Parse 07 36.9
HMS  Parse 01 29.5
HMS  Parse 22 56.8
HMS  Parse 01 46.0
HMS  Parse 23 20.7
HMS  Parse 20 34.8
HMS  Parse 01 19.1
HMS  Parse 02 20.0
HMS  Parse 19 44.8
HMS  Parse 22 15.3
HMS  Parse 00 33.2
HMS  Parse 00 39.0
HMS  Parse 21 53.5
HMS  Parse 20 58.8
HMS  Parse 12 28.2
HMS  Parse 23 25.9
HMS  Parse 02 22.6
HMS  Parse 03 19.8
HMS  Parse 07 38.1
HMS  Parse 12 17.5
HMS  Parse 20 12.0
HMS  Parse 01 57.8
HMS  Parse 13 10.9
HMS  Parse 22 37.1
HMS  Parse 05 16.2
HMS  Parse 12 42.1
HMS  Parse 20 56.4
HMS  Parse 20 45.7
HMS  Parse 13 00.1
HMS  Parse 12 36.0
HMS  Parse 20 12.0
HMS  Parse 12 36.3
HMS  Parse 07 29.2
HMS  Parse 11 20.1
HMS  Parse 04 27.0
HMS  Parse 21 01.5
HMS  Parse 00 03.3
HMS  Parse 23 04.9
HMS  Parse 13 37.5
HMS  Parse 06 39.2
HMS  Parse 20 34.2
HMS  Parse 09 10.3
HMS  Parse 06 32.3
HMS  Parse 06 32.4
HMS  Parse 01 04.8
HMS  Parse 12 48.6
HMS  Parse 10 05.2
HMS  Parse 08 00.2
HMS  Parse 21 04.2
HMS  Parse 00 47.0
HMS  Parse 19 44.9
HMS  Parse 07 17.8
HMS  Parse 10 24.8
HMS  Parse 12 01.9
HMS  Parse 12 01.9
HMS  Parse 00 47.1
HMS  Parse 22 29.6
HMS  Parse 07 18.8
HMS  Parse 00 47.6
HMS  Parse 14 39.6
HMS  Parse 02 46.3
HMS  Parse 19 01.9
HMS  Parse 17 13.7
HMS  Parse 00 54.9
HMS  Parse 07 52.3
HMS  Parse 00 14.9
HMS  Parse 05 14.1
HMS  Parse 10 07.7
HMS  Parse 16 25.6
HMS  Parse 16 54.0
HMS  Parse 13 25.5
HMS  Parse 18 08.0
HMS  Parse 10 17.6
HMS  Parse 13 26.8
HMS  Parse 17 25.5
HMS  Parse 16 41.3
HMS  Parse 13 05.4
HMS  Parse 13 46.4
HMS  Parse 08 40.2
HMS  Parse 17 40.7
HMS  Parse 03 12.3
HMS  Parse 15 05.7
HMS  Parse 16 18.9
HMS  Parse 09 21.4
HMS  Parse 11 06.4
HMS  Parse 10 43.8
HMS  Parse 19 10.9
HMS  Parse 12 53.6
HMS  Parse 16 03.7
HMS  Parse 07 58.3
HMS  Parse 11 36.1
HMS  Parse 12 42.3
HMS  Parse 12 53.0
HMS  Parse 11 36.6
HMS  Parse 19 09.8
HMS  Parse 10 43.2
HMS  Parse 05 38.7
HMS  Parse 01 03.2
HMS  Parse 12 59.6
HMS  Parse 00 24.1
HMS  Parse 16 25.8
HMS  Parse 12 25.8
HMS  Parse 10 09.5
DEC  Parse +85 20
DEC  Parse +72 32
DEC  Parse +69 28
DEC  Parse +68 12
DEC  Parse +68 06
DEC  Parse +66 38
DEC  Parse +65 36
DEC  Parse +63 18
DEC  Parse +62 37
DEC  Parse +61 15
DEC  Parse +61 12
DEC  Parse +60 09
DEC  Parse +58 20
DEC  Parse +57 08
DEC  Parse +50 31
DEC  Parse +49 53
DEC  Parse +48 30
DEC  Parse +48 20
DEC  Parse +47 16
DEC  Parse +44 20
DEC  Parse +44 06
DEC  Parse +42 33
DEC  Parse +42 21
DEC  Parse +41 31
DEC  Parse +38 53
DEC  Parse +37 49
DEC  Parse +38 21
DEC  Parse +37 41
DEC  Parse +37 03
DEC  Parse +34 25
DEC  Parse +34 16
DEC  Parse +32 32
DEC  Parse +31 43
DEC  Parse +30 43
DEC  Parse +27 59
DEC  Parse +27 58
DEC  Parse +26 29
DEC  Parse +25 59
DEC  Parse +20 55
DEC  Parse +18 21
DEC  Parse +16 00
DEC  Parse +16 11
DEC  Parse +16 09
DEC  Parse +12 19
DEC  Parse +08 53
DEC  Parse +08 44
DEC  Parse +07 24
DEC  Parse +07 02
DEC  Parse +05 03
DEC  Parse +04 52
DEC  Parse +02 07
DEC  Parse -05 48
DEC  Parse -07 43
DEC  Parse -10 47
DEC  Parse -11 22
DEC  Parse -11 53
DEC  Parse -14 48
DEC  Parse -15 37
DEC  Parse -18 38
DEC  Parse -18 52
DEC  Parse -18 53
DEC  Parse -20 46
DEC  Parse -20 48
DEC  Parse -24 57
DEC  Parse -25 17
DEC  Parse -26 32
DEC  Parse -30 17
DEC  Parse -36 57
DEC  Parse -37 06
DEC  Parse -37 41
DEC  Parse -38 33
DEC  Parse -39 11
DEC  Parse -40 03
DEC  Parse -40 26
DEC  Parse -40 40
DEC  Parse -41 48
DEC  Parse -43 01
DEC  Parse -43 42
DEC  Parse -46 25
DEC  Parse -47 29
DEC  Parse -48 25
DEC  Parse -48 46
DEC  Parse -49 28
DEC  Parse -51 22
DEC  Parse -53 04
DEC  Parse -53 40
DEC  Parse -55 13
DEC  Parse -55 36
DEC  Parse -57 54
DEC  Parse -58 19
DEC  Parse -58 40
DEC  Parse -59 52
DEC  Parse -59 59
DEC  Parse -60 20
DEC  Parse -60 30
DEC  Parse -60 52
DEC  Parse -61 37
DEC  Parse -62 58
DEC  Parse -63 00
DEC  Parse -63 02
DEC  Parse -63 51
DEC  Parse -64 24
DEC  Parse -69 06
DEC  Parse -70 51
DEC  Parse -70 53
DEC  Parse -72 05
DEC  Parse -72 12
DEC  Parse -72 40
DEC  Parse -80 52

In [5]:
df.rename(columns={"Common Name":"Alt_name"})

,C,NGC,Type,Mag.,Size arc_min,Distance (ly),RA (hr_min),Dec (dg_min),Con,Viewing Season,Alt_name,RA_2,DEC_2
0,1,188,Oc,8.1,14,4800,00 44.4,+85 20,Cep,autumn,188,11.100,85.333333
1,2,40,Pl,11.6,0.6,3500,00 13.0,+72 32,Cep,autumn,Bow Tie Nebula,3.250,72.533333
2,3,4236,Sb,9.7,21x7,7 million,12 16.7,+69 28,Dra,spring,4236,184.175,69.466667
3,4,7023,Bn,6.8,18x18,1400,21 01.8,+68 12,Cep,autumn,Iris Nebula,315.450,68.200000
4,5,IC 342,Sp,9.2,18x17,13 million,03 46.8,+68 06,Cam,winter,IC 342,56.700,68.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,105,4833,Gc,7.3,14,19600,12 59.6,-70 53,Mus,spring,4833,194.900,-70.883333
105,106,104,Gc,4.0,31,14700,00 24.1,-72 05,Tuc,autumn,47 Tucanae,6.025,-72.083333
106,107,6101,Gc,9.3,11,49900,16 25.8,-72 12,Aps,summer,6101,246.450,-72.200000
107,108,4372,Gc,7.8,19,18900,12 25.8,-72 40,Mus,spring,4372,186.450,-72.666667
108,109,3195,Pl,11.6,40_35,5400,10 09.5,-80 52,Cha,spring,3195,152.375,-80.866667

In [6]:
# This is from the C++ Code
        # KStars 3.8
KSTARS_TYPE_MAP = {
            # Stars
            "STAR": 1,
            "S": 1,
            "TYCHO": 1,
            # Solar system
            "PLANET": 2,
            "ASTEROID": 10,
            "COMET": 9,
            "SATELLITE": 16,
            # Clusters
            "OPEN": 3,
            "OPEN_CLUSTER": 3,
            "OC": 3,
            "GLOBULAR": 4,
            "GC": 4,
            "GLOBULAR_CLUSTER": 4,
            # Nebulae
            "GASEOUS": 5,
            "HII": 5,
            "DIFFUSE": 5,
            "EMISSION": 5,
            "PLANETARY": 6,
            "PN": 6,
            "SUPERNOVA_REMNANT": 7,
            "SNR": 7,
            # Galaxies
            "GALAXY": 8,
            "G": 8,
            "CLUSTER": 14,  # galaxy clusters
            "QUASAR": 15,
        }


mapping = {
    "Oc":KSTARS_TYPE_MAP["OPEN_CLUSTER"],
    "Gc":KSTARS_TYPE_MAP["OPEN_CLUSTER"],
    "Sp":KSTARS_TYPE_MAP["GALAXY"],    #Spiral Galaxy
    "Pl":KSTARS_TYPE_MAP["PLANETARY"],
    "Bn":KSTARS_TYPE_MAP["EMISSION"],
    "Sb":KSTARS_TYPE_MAP["GALAXY"],  # Inclined Spiral Galaxy ?
    "El":KSTARS_TYPE_MAP["CLUSTER"], #Super Eliptical Galaxy
    "Ir":KSTARS_TYPE_MAP["GALAXY"],# irregular dwarf galaxy
    "Sn":KSTARS_TYPE_MAP["SUPERNOVA_REMNANT"],
    "Sx":KSTARS_TYPE_MAP["QUASAR"],#Seyfert galaxy - Quasar
    "Px":KSTARS_TYPE_MAP["GALAXY"],#Lenticular galaxy
    "Dn":KSTARS_TYPE_MAP["GASEOUS"] #Dark Nebulae
}

In [7]:
print("Finished loading the Data")
df["KStars_Type"] = df["Type"].map(mapping)

Finished loading the Data

In [8]:
df['Type'].value_counts()

Type
Oc    28
Gc    18
Sp    14
Pl    13
Bn    12
Sb    11
El     5
Ir     3
Sn     2
Sx     1
Px     1
Dn     1
Name: count, dtype: int64

In [9]:
df['KStars_Type'].value_counts()

KStars_Type
3     46
8     29
6     13
5     13
14     5
7      2
15     1
Name: count, dtype: int64

In [10]:
df.head()

,C,NGC,Type,Mag.,Size arc_min,Distance (ly),RA (hr_min),Dec (dg_min),Con,Viewing Season,Common Name,RA_2,DEC_2,KStars_Type
0,1,188,Oc,8.1,14,4800,00 44.4,+85 20,Cep,autumn,188,11.100,85.333333,3
1,2,40,Pl,11.6,0.6,3500,00 13.0,+72 32,Cep,autumn,Bow Tie Nebula,3.250,72.533333,6
2,3,4236,Sb,9.7,21x7,7 million,12 16.7,+69 28,Dra,spring,4236,184.175,69.466667,8
3,4,7023,Bn,6.8,18x18,1400,21 01.8,+68 12,Cep,autumn,Iris Nebula,315.450,68.200000,5
4,5,IC 342,Sp,9.2,18x17,13 million,03 46.8,+68 06,Cam,winter,IC 342,56.700,68.100000,8

In [11]:
df['tmp_name'] = df['Common Name'].fillna(df['NGC'])

In [12]:
df

,C,NGC,Type,Mag.,Size arc_min,Distance (ly),RA (hr_min),Dec (dg_min),Con,Viewing Season,Common Name,RA_2,DEC_2,KStars_Type,tmp_name
0,1,188,Oc,8.1,14,4800,00 44.4,+85 20,Cep,autumn,188,11.100,85.333333,3,188
1,2,40,Pl,11.6,0.6,3500,00 13.0,+72 32,Cep,autumn,Bow Tie Nebula,3.250,72.533333,6,Bow Tie Nebula
2,3,4236,Sb,9.7,21x7,7 million,12 16.7,+69 28,Dra,spring,4236,184.175,69.466667,8,4236
3,4,7023,Bn,6.8,18x18,1400,21 01.8,+68 12,Cep,autumn,Iris Nebula,315.450,68.200000,5,Iris Nebula
4,5,IC 342,Sp,9.2,18x17,13 million,03 46.8,+68 06,Cam,winter,IC 342,56.700,68.100000,8,IC 342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,105,4833,Gc,7.3,14,19600,12 59.6,-70 53,Mus,spring,4833,194.900,-70.883333,3,4833
105,106,104,Gc,4.0,31,14700,00 24.1,-72 05,Tuc,autumn,47 Tucanae,6.025,-72.083333,3,47 Tucanae
106,107,6101,Gc,9.3,11,49900,16 25.8,-72 12,Aps,summer,6101,246.450,-72.200000,3,6101
107,108,4372,Gc,7.8,19,18900,12 25.8,-72 40,Mus,spring,4372,186.450,-72.666667,3,4372
108,109,3195,Pl,11.6,40_35,5400,10 09.5,-80 52,Cha,spring,3195,152.375,-80.866667,6,3195

In [13]:
#df['ra_degrees']=df.RA_2/24.0*360.0

In [14]:
df

,C,NGC,Type,Mag.,Size arc_min,Distance (ly),RA (hr_min),Dec (dg_min),Con,Viewing Season,Common Name,RA_2,DEC_2,KStars_Type,tmp_name
0,1,188,Oc,8.1,14,4800,00 44.4,+85 20,Cep,autumn,188,11.100,85.333333,3,188
1,2,40,Pl,11.6,0.6,3500,00 13.0,+72 32,Cep,autumn,Bow Tie Nebula,3.250,72.533333,6,Bow Tie Nebula
2,3,4236,Sb,9.7,21x7,7 million,12 16.7,+69 28,Dra,spring,4236,184.175,69.466667,8,4236
3,4,7023,Bn,6.8,18x18,1400,21 01.8,+68 12,Cep,autumn,Iris Nebula,315.450,68.200000,5,Iris Nebula
4,5,IC 342,Sp,9.2,18x17,13 million,03 46.8,+68 06,Cam,winter,IC 342,56.700,68.100000,8,IC 342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,105,4833,Gc,7.3,14,19600,12 59.6,-70 53,Mus,spring,4833,194.900,-70.883333,3,4833
105,106,104,Gc,4.0,31,14700,00 24.1,-72 05,Tuc,autumn,47 Tucanae,6.025,-72.083333,3,47 Tucanae
106,107,6101,Gc,9.3,11,49900,16 25.8,-72 12,Aps,summer,6101,246.450,-72.200000,3,6101
107,108,4372,Gc,7.8,19,18900,12 25.8,-72 40,Mus,spring,4372,186.450,-72.666667,3,4372
108,109,3195,Pl,11.6,40_35,5400,10 09.5,-80 52,Cha,spring,3195,152.375,-80.866667,6,3195